### ISSUE TITLE
Mastodon doesn't start when deployed

### ISSUE THREAD

**Issue by marcoacierno** [tmm1/flyapp-mastodon#5]
Hello!

I tried using this repo to deploy Mastodon and one issue I had was that going to the URL caused it to hang/not show anything. It was a few days ago so I don't 100% remember what was the result, I remember it just hanging and doing nothing even if the monitoring page said that the "server started on 3000".

I was able to fix by removing the `processes = ["rails"]` in the `[[services]]` block (https://github.com/marcotteteam/marcotte.party/commit/2c1d5c32011583bb4ed15225a874ef479c10f9e0)

I wonder if anyone else had a similar problem and if removing this `processes` is the right fix?

**Comment by indirect** [comment]
You're right! Sorry I missed that.
